filter:
    excluded_paths: [ "vendor/*", "tests/*" ]

build:
    environment:
        php: 7.1.12
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
